###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

[database]

# db host for docker-compose
url = "host=localhost port=5432 user=postgres password=postgres dbname=jobs_db sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# RabbitMQ configuration

[rabbitmq]

rabbitmq_instance_type = "publisher"
rabbitmq_url = "amqp://guest:guest@localhost:5672/"

###############################################################################
# CORS configuration

[cors]

allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

###############################################################################
# S3 configuration

[s3]

bucket_name = "scheduler-bucket"
region = "us-east-1"
access_key_id = "access_key_id"
